services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data-mount:/data/db # Persist data through mounted volume
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-user
      - MONGO_INITDB_ROOT_PASSWORD=mongo-pass

  messaging:
    image: rabbitmq:3.11-management
    ports:
      - 8081:15672

  storage_service:
    build: storage_service
    depends_on:
      - messaging

      # - QUERY_INTERVAL=3600

  reddit_endpoint_adapter:
    build: endpoint_adapters
    depends_on:
      - messaging
    environment:
      - ENDPOINT_TYPE=reddit
      - CHANNEL_NAME=messaging
      - NEW_REVIEW_OUT=new_review
      - NEW_TITLE_IN=new_title
      - QUERY_INTERVAL=3600
      # Get your client ID / Secret here: https://ssl.reddit.com/prefs/apps/
      # - REDDIT_CLIENT_ID=
      # - REDDIT_CLIENT_SECRET=
      # - REDDIT_USER_AGENT=eai:reddit_adapter:0.1 (by /u/willem88836)

  imdb_endpoint_adapter:
    build: endpoint_adapters
    depends_on:
      - messaging
    environment:
      - ENDPOINT_TYPE=imdb
      - CHANNEL_NAME=messaging
      - NEW_REVIEW_OUT=new_review
      - NEW_TITLE_IN=new_title

  twitter_endpoint_adapter:
    build: endpoint_adapters
    depends_on:
      - messaging
    environment:
      - ENDPOINT_TYPE=twitter
      - CHANNEL_NAME=messaging
      - NEW_REVIEW_OUT=new_review
      - NEW_TITLE_IN=new_title
      - QUERY_INTERVAL=3600
      - TWITTER_BEARER_TOKEN=
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
        - ./:/app:cached
        
  sentistrength_adapter:
    build: sentistrength_adapter
    depends_on:
      - messaging
    environment:
      - CHANNEL_NAME=messaging
      - NEW_REVIEW_IN=new_review
      - NEW_SENTIMENT_OUT=new_sentiment
      - CLASSIFICATION_TYPE=scale

  title_finder:
    build: title_finder
    depends_on: 
      - messaging
    environment:
      - CHANNEL_NAME=messaging
      # For details checkout https://developers.themoviedb.org/3/getting-started/introduction
      - TMDB_API_KEY=
      - SLEEP_INTERVAL=86400
      - CHANNEL=messaging
      - NEW_TITLE_OUT=new_title
      - START_DELAY=0
