services:

  api:
    build: ./test_rest_api
    ports:
      - "5000:5000"

  api-adapter:
    build: ./test_rest_api_adapter
    depends_on: 
      - api
    network_mode: "host"

  # senti-adapter:
  #   build: ./sentistrength
