services:
  mongodb:
    image: mongo:6.0
    ports:
      - 27017:27017
    volumes:
      - ./mongo/data-mount:/data/db # Persist data through mounted volume
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo-user
      - MONGO_INITDB_ROOT_PASSWORD=mongo-pass

  messaging:
    image: rabbitmq:3.11-management
    ports:
      - 8081:15672

  storage_service:
    build: storage_service
    depends_on:
      - messaging

  # test_endpoint_adapter:
  #   build: endpoint_adapters
  #   depends_on:
  #     - messaging
  #   environment:
  #     - ENDPOINT_TYPE=test
  #     - CHANNEL_NAME=messaging
  #     - QUEUE_NAME=new_review
  #     - UPDATE_INTERVAL=10

  reddit_endpoint_adapter:
    build: endpoint_adapters
    depends_on:
      - messaging
    environment:
      - ENDPOINT_TYPE=reddit
      - CHANNEL_NAME=messaging
      - QUEUE_NAME=new_review
      - UPDATE_INTERVAL=3600
      # Get your client ID / Secret here: https://ssl.reddit.com/prefs/apps/
      - REDDIT_CLIENT_ID=pgF2sXW4dYR9upp4FMYNhA
      - REDDIT_CLIENT_SECRET=fLvx_m65iRceZQ9a-L4aL4nH2mHFiQ
      - REDDIT_USER_AGENT=eai:reddit_adapter:0.1 (by /u/willem88836)

  imdb_endpoint_adapter:
    build: endpoint_adapters
    depends_on:
      - messaging
    environment:
      - ENDPOINT_TYPE=imdb
      - CHANNEL_NAME=messaging
      - QUEUE_NAME=new_review
      - UPDATE_INTERVAL=120

  twitter_endpoint_adapter:
    build: endpoint_adapters
    depends_on:
      - messaging
    environment:
      - ENDPOINT_TYPE=twitter
      - CHANNEL_NAME=messaging
      - QUEUE_NAME=new_review
      - UPDATE_INTERVAL=3600
      - TWITTER_BEARER_TOKEN=
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
        - ./:/app:cached
        
  sentistrength_adapter:
    build: sentistrength_adapter
    depends_on:
      - messaging
    environment:
      - CHANNEL_NAME=messaging
      - IN_QUEUE_NAME=new_review
      - OUT_QUEUE_NAME=new_sentiment
      - CLASSIFICATION_TYPE=scale
