services:

  messaging:
    image: rabbitmq:3.11-management
    ports:
      - 8081:15672

  rabbit_test:
    build: rabbit
    depends_on:
      - messaging
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./:/app:cached

  endpoint_adapters:
    build: endpoint_adapters
    depends_on:
      - messaging
    command: /bin/sh -c "while sleep 1000; do :; done"
    volumes:
      - ./:/app:cached
