global:
  scrape_interval: 15s # Default is every 1 minute.

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # - job_name: 'docker'
  #   static_configs:
  #     - targets: ['docker.for.mac.localhost:9323']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'rabbitmq-server'
    static_configs:
      - targets:
          - 'messaging:15692'
  - job_name: 'mongo'
    static_configs:
      - targets:
          - 'mongodb-exporter:9216'
